language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-api-feed opals/udagram-api-feed:latest # tag images
  - docker tag udagram-api-user opals/udagram-api-user:latest
  - docker tag reverseproxy opals/reverseproxy:latest
  - docker tag udagram-frontend opals/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push opals/udagram-api-user:latest
  - docker push opals/udagram-api-feed:latest
  - docker push opals/reverseproxy:latest
  - docker push opals/udagram-frontend:latest
