apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: opals/udagram-api-feed
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: mysecret
        - configMapRef:
            name: myconfig
        ports:
        - containerPort: 8100
        livenessProbe:
          httpGet:
            path: /health
            port: 8100
          initialDelaySeconds: 3
          periodSeconds: 3
