apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-user
  name: backend-user-svc
spec:
  ports:
  - name: "8080"
    port: 8100
    targetPort: 8100
  selector:
    service: backend-user
